name: Android CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      working-directory: app
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: app
      run: mkdir -p build && ./gradlew build --stacktrace --info 2> build/results.txt
      continue-on-error: true
      id: build

    - name: Test
      working-directory: app
      run: mkdir -p build && ./gradlew test 2> build/results-test.txt
      continue-on-error: true
      id: test

    - name: Get build results
      working-directory: app
      if: steps.build.outcome == 'failure'
      run: echo "BUILD_RESULT=$(sed ':a;N;$!ba;s/\n/ /g' build/results.txt)" >> $GITHUB_ENV
      continue-on-error: true

    - name: Get test results
      working-directory: app
      if: steps.test.outcome == 'failure'
      run: echo "TEST_RESULT=$(sed ':a;N;$!ba;s/\n/ /g' build/results-test.txt)" >> $GITHUB_ENV
      continue-on-error: true

    - name: Create PR comment
      working-directory: app
      if: steps.build.outcome == 'failure' || steps.test.outcome == 'failure'
      uses: actions/github-script@v6
      with:
        script: |
          const pr = context.payload.pull_request;
          if (!pr) {
            console.log('No es una Pull Request');
            return;
          }
          
          var buildResult = "";
          var testResult = "";
          if (process.env.BUILD_RESULT) {
            buildResult = process.env.BUILD_RESULT.replace(/(?:\r\n|\r|\n)/g, ' ');
          }

          if (process.env.TEST_RESULT) {
            testResult = process.env.TEST_RESULT.replace(/(?:\r\n|\r|\n)/g, ' ');
          }

          const issueComment = 'El pull request fallo con el siguiente error: \n```\n' + buildResult + testResult + '\n```\n';
          github.rest.issues.createComment({
            issue_number: pr.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: issueComment
          });
          core.setFailed('Se agregó un comentario en el PR sobre el fallo.')
    
